function updateGRidView {

        $dataGridView1.ColumnCount=4
        $dataGridView1.Rows.clear();
        $command = New-Object MySql.Data.MySqlClient.MySqlCommand;
        $command.Connection = $conn;
        $command.CommandText = "select * FROM devices";
        $reader = $command.ExecuteReader();
        while($reader.Read())
        {
            $row = @("MAC","IP","Date","Bemerkungen");
            $row[0]=$reader.GetString(0)        
            $row[1]=$reader.GetString(1)        
            $row[2]=$reader.GetString(2)
            try {
                $bem =$reader.GetString(3)         
                $row[3]=$bem
            }
            catch {
                $row[3]="-";
            }
            $dataGridView1.Rows.add($row)
        }
        $reader.Close();

}
#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 24.05.2016 12:05
# Generated By: Jörg
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$Devices = New-Object System.Windows.Forms.Form
$btnSaceQR = New-Object System.Windows.Forms.Button
$pictureBox1 = New-Object System.Windows.Forms.PictureBox
$dataGridView1 = New-Object System.Windows.Forms.DataGridView
$tbBem = New-Object System.Windows.Forms.TextBox
$tbIp = New-Object System.Windows.Forms.TextBox
$tbMac = New-Object System.Windows.Forms.TextBox
$btnQr = New-Object System.Windows.Forms.Button
$btnDelete = New-Object System.Windows.Forms.Button
$btnUpdate = New-Object System.Windows.Forms.Button
$label3 = New-Object System.Windows.Forms.Label
$label2 = New-Object System.Windows.Forms.Label
$label1 = New-Object System.Windows.Forms.Label
$saveFileDialog1 = New-Object System.Windows.Forms.SaveFileDialog
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$delete= 
{
    $command = New-Object MySql.Data.MySqlClient.MySqlCommand;
    $command.Connection = $conn;    
    $command.CommandText = "Delete from devices WHERE mac='"+$tbMac.Text+"'"
    $res=$command.ExecuteNonQuery();
    updateGridView
    $tbMac.Text=$dataGridView1.Rows[$dataGridView1.SelectedCells[0].RowIndex].Cells[0].Value
    $tbIp.Text=$dataGridView1.Rows[$dataGridView1.SelectedCells[0].RowIndex].Cells[1].Value
    $tbBem.Text=$dataGridView1.Rows[$dataGridView1.SelectedCells[0].RowIndex].Cells[3].Value
   
}

$update= 
{
    $command = New-Object MySql.Data.MySqlClient.MySqlCommand;
    $command.Connection = $conn;    
    $command.CommandText = "UPDATE devices SET ip='"+$tbIp.Text+"',msg='"+$tbBem.Text+"'  WHERE mac='"+$tbMac.Text+"'"
    $res=$command.ExecuteNonQuery();
    updateGridView

}

$saveQr= 
{
#TODO: Place custom script here
$saveFileDialog1.ShowDialog();
if ($saveFileDialog1.FileName) {
    $text = "MAC:"+$tbMac.Text+" Bemerkung:"+$tbBem.Text
    Start-BitsTransfer -Source "https://chart.googleapis.com/chart?cht=qr&chl=$text&chs=150x150" -Destination $saveFileDialog1.FileName
}
Write-Host $saveFileDialog1.FileName

}

$genQr= 
{
$text = "MAC:"+$tbMac.Text+" Bemerkung:"+$tbBem.Text
$r=Get-Random -Minimum 100000
$file="qr$r.jpg"
Start-BitsTransfer -Source "https://chart.googleapis.com/chart?cht=qr&chl=$text&chs=150x150" -Destination $PSScriptRoot\$file 
$pictureBox1.Image =[System.Drawing.Image]::FromFile("$PSScriptRoot\$file");

}

$cellClick= 
{
Write-Host "Cell Click:"$dataGridView1.SelectedCells[0].RowIndex
$tbMac.Text=$dataGridView1.Rows[$dataGridView1.SelectedCells[0].RowIndex].Cells[0].Value
$tbIp.Text=$dataGridView1.Rows[$dataGridView1.SelectedCells[0].RowIndex].Cells[1].Value
$tbBem.Text=$dataGridView1.Rows[$dataGridView1.SelectedCells[0].RowIndex].Cells[3].Value

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$Devices.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 324
$System_Drawing_Size.Width = 572
$Devices.ClientSize = $System_Drawing_Size
$Devices.DataBindings.DefaultDataSourceUpdateMode = 0
$Devices.Name = "Devices"
$Devices.Text = "Devices"


$btnSaceQR.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 95
$System_Drawing_Point.Y = 289
$btnSaceQR.Location = $System_Drawing_Point
$btnSaceQR.Name = "btnSaceQR"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 137
$btnSaceQR.Size = $System_Drawing_Size
$btnSaceQR.TabIndex = 12
$btnSaceQR.Text = "Save QR"
$btnSaceQR.UseVisualStyleBackColor = $True
$btnSaceQR.add_Click($saveQr)

$Devices.Controls.Add($btnSaceQR)


$pictureBox1.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 413
$System_Drawing_Point.Y = 177
$pictureBox1.Location = $System_Drawing_Point
$pictureBox1.Name = "pictureBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 135
$System_Drawing_Size.Width = 143
$pictureBox1.Size = $System_Drawing_Size
$pictureBox1.TabIndex = 11
$pictureBox1.TabStop = $False

$Devices.Controls.Add($pictureBox1)

$dataGridView1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 13
$dataGridView1.Location = $System_Drawing_Point
$dataGridView1.Name = "dataGridView1"
$dataGridView1.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 158
$System_Drawing_Size.Width = 543
$dataGridView1.Size = $System_Drawing_Size
$dataGridView1.TabIndex = 10
$dataGridView1.add_CellClick($cellClick)

$Devices.Controls.Add($dataGridView1)

$tbBem.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 94
$System_Drawing_Point.Y = 230
$tbBem.Location = $System_Drawing_Point
$tbBem.Name = "tbBem"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 220
$tbBem.Size = $System_Drawing_Size
$tbBem.TabIndex = 9

$Devices.Controls.Add($tbBem)

$tbIp.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 94
$System_Drawing_Point.Y = 203
$tbIp.Location = $System_Drawing_Point
$tbIp.Name = "tbIp"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 220
$tbIp.Size = $System_Drawing_Size
$tbIp.TabIndex = 8

$Devices.Controls.Add($tbIp)

$tbMac.DataBindings.DefaultDataSourceUpdateMode = 0
$tbMac.Enabled = $False
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 94
$System_Drawing_Point.Y = 177
$tbMac.Location = $System_Drawing_Point
$tbMac.Name = "tbMac"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 220
$tbMac.Size = $System_Drawing_Size
$tbMac.TabIndex = 7

$Devices.Controls.Add($tbMac)


$btnQr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 94
$System_Drawing_Point.Y = 256
$btnQr.Location = $System_Drawing_Point
$btnQr.Name = "btnQr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 138
$btnQr.Size = $System_Drawing_Size
$btnQr.TabIndex = 6
$btnQr.Text = "Generate QR Code"
$btnQr.UseVisualStyleBackColor = $True
$btnQr.add_Click($genQr)

$Devices.Controls.Add($btnQr)


$btnDelete.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 289
$btnDelete.Location = $System_Drawing_Point
$btnDelete.Name = "btnDelete"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$btnDelete.Size = $System_Drawing_Size
$btnDelete.TabIndex = 5
$btnDelete.Text = "Delete"
$btnDelete.UseVisualStyleBackColor = $True
$btnDelete.add_Click($delete)

$Devices.Controls.Add($btnDelete)


$btnUpdate.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 256
$btnUpdate.Location = $System_Drawing_Point
$btnUpdate.Name = "btnUpdate"
$btnUpdate.RightToLeft = 1
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$btnUpdate.Size = $System_Drawing_Size
$btnUpdate.TabIndex = 4
$btnUpdate.Text = "Update"
$btnUpdate.UseVisualStyleBackColor = $True
$btnUpdate.add_Click($update)

$Devices.Controls.Add($btnUpdate)

$label3.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 230
$label3.Location = $System_Drawing_Point
$label3.Name = "label3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$label3.Size = $System_Drawing_Size
$label3.TabIndex = 3
$label3.Text = "Bemerkungen"

$Devices.Controls.Add($label3)

$label2.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 203
$label2.Location = $System_Drawing_Point
$label2.Name = "label2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$label2.Size = $System_Drawing_Size
$label2.TabIndex = 2
$label2.Text = "IP"

$Devices.Controls.Add($label2)

$label1.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 180
$label1.Location = $System_Drawing_Point
$label1.Name = "label1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$label1.Size = $System_Drawing_Size
$label1.TabIndex = 1
$label1.Text = "MAC"

$Devices.Controls.Add($label1)

$saveFileDialog1.CreatePrompt = $False
$saveFileDialog1.ShowHelp = $True
$saveFileDialog1.Filter = "Bilder|*.jpg"


#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $Devices.WindowState
#Init the OnLoad event to correct the initial state of the form
$Devices.add_Load($OnLoadForm_StateCorrection)
[xml]$config = get-content "$PSScriptRoot\config.xml" -ErrorAction SilentlyContinue

        #Store Connection parameters
        $connString = "Server="+$config.config.dbserver+";Uid="+$config.config.dbuser+";Pwd="+$config.config.dbpassword+";database="+$config.config.dbname;
        # load MySQL-Connector from assembly, don't use .dll in library name even if it's listed like this in the assembly path
        $r=[reflection.Assembly]::LoadWithPartialname("mysql.data");
        # create a new MySQL-connection object
        $conn = New-Object MySql.Data.MySqlClient.MySqlConnection;
        # link the connection parameters to the connection object
        $conn.ConnectionString = $connString;
        # finally: open the connection
        $conn.Open();
        updateGridView
        $tbMac.Text=$dataGridView1.Rows[0].Cells[0].Value
        $tbIp.Text=$dataGridView1.Rows[0].Cells[1].Value
        $tbBem.Text=$dataGridView1.Rows[0].Cells[3].Value

    


#Show the Form
$Devices.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
