#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 24.01.2014 14:17
# Generated By: Joerg-T400
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$label2 = New-Object System.Windows.Forms.Label
$textBox4 = New-Object System.Windows.Forms.TextBox
$receivetextBox = New-Object System.Windows.Forms.TextBox
$sendtextBox = New-Object System.Windows.Forms.TextBox
$statusBar1 = New-Object System.Windows.Forms.StatusBar
$button1 = New-Object System.Windows.Forms.Button
$label1 = New-Object System.Windows.Forms.Label
$textBox1 = New-Object System.Windows.Forms.TextBox
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects
$sendtextBox.Enabled=$false



#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$keyPressed= 
{
#TODO: Place custom script here
    
    if ($_.KeyCode -eq "Return" -and $connected) {
        $sendtextBox.Enabled=$false
        $b=[Text.Encoding]::ASCII.GetBytes($sendtextBox.Text)
        $bytesSent=$global:udpclient.Send($b,$b.length,$global:endpoint)
        $sendtextBox.Text=""

        $content=$udpclient.Receive([ref]$gloabl:endpoint)
        $b=[Text.Encoding]::ASCII.GetString($content)
        #Write-Host "Empfange $b"
        $receivetextBox.AppendText("`r`n$b")
        $sendtextBox.Enabled=$true
    }
}

$connect= 
{
#TODO: Place custom script here
    if ($global:connected) {
        $global:udpclient.Close();
        $statusBar1.Text="disconnected"
        $button1.Text="connect"
        $global:connected=$false;
        $sendtextBox.Enabled=$false
    }
    else {
        $global:port=$textBox4.Text
        $global:endpoint = new-object System.Net.IPEndPoint ([IPAddress]$textBox1.Text,$global:port)
        $global:udpclient=new-Object System.Net.Sockets.UdpClient 
        $b=[Text.Encoding]::ASCII.GetBytes('Login')
        $bytesSent=$global:udpclient.Send($b,$b.length,$endpoint)

        $content=$udpclient.Receive([ref]$endpoint)
        $b=[Text.Encoding]::ASCII.GetString($content)
        #Write-Host "Empfange $b"
        $receivetextBox.AppendText("`r`n$b")
        $statusBar1.Text="Connected"
        $button1.Text="disconnect"
        $sendtextBox.Enabled=$true
        $global:connected=$true;
    }
}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 230
$System_Drawing_Size.Width = 429
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "Chat Client"

$label2.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 183
$System_Drawing_Point.Y = 15
$label2.Location = $System_Drawing_Point
$label2.Name = "label2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 38
$label2.Size = $System_Drawing_Size
$label2.TabIndex = 7
$label2.Text = "Port:"

$form1.Controls.Add($label2)

$textBox4.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 227
$System_Drawing_Point.Y = 12
$textBox4.Location = $System_Drawing_Point
$textBox4.Name = "textBox4"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 59
$textBox4.Size = $System_Drawing_Size
$textBox4.TabIndex = 6
$textBox4.Text = "2022"

$form1.Controls.Add($textBox4)

$receivetextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 39
$receivetextBox.Location = $System_Drawing_Point
$receivetextBox.Multiline = $True
$receivetextBox.Name = "receivetextBox"
$receivetextBox.ReadOnly = $True
$receivetextBox.ScrollBars = 3
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 137
$System_Drawing_Size.Width = 404
$receivetextBox.Size = $System_Drawing_Size
$receivetextBox.TabIndex = 5

$form1.Controls.Add($receivetextBox)

$sendtextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 182
$sendtextBox.Location = $System_Drawing_Point
$sendtextBox.Name = "sendtextBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 404
$sendtextBox.Size = $System_Drawing_Size
$sendtextBox.TabIndex = 4
$sendtextBox.add_KeyDown($keyPressed)

$form1.Controls.Add($sendtextBox)

$statusBar1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 0
$System_Drawing_Point.Y = 208
$statusBar1.Location = $System_Drawing_Point
$statusBar1.Name = "statusBar1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 22
$System_Drawing_Size.Width = 429
$statusBar1.Size = $System_Drawing_Size
$statusBar1.TabIndex = 3
$statusBar1.Text = "please connect"

$form1.Controls.Add($statusBar1)


$button1.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 331
$System_Drawing_Point.Y = 12
$button1.Location = $System_Drawing_Point
$button1.Name = "button1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 86
$button1.Size = $System_Drawing_Size
$button1.TabIndex = 2
$button1.Text = "connect"
$button1.UseVisualStyleBackColor = $True
$button1.add_Click($connect)

$form1.Controls.Add($button1)

$label1.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 15
$label1.Location = $System_Drawing_Point
$label1.Name = "label1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 59
$label1.Size = $System_Drawing_Size
$label1.TabIndex = 1
$label1.Text = "Server IP"

$form1.Controls.Add($label1)

$textBox1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 78
$System_Drawing_Point.Y = 12
$textBox1.Location = $System_Drawing_Point
$textBox1.Name = "textBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 99
$textBox1.Size = $System_Drawing_Size
$textBox1.TabIndex = 0
$textBox1.Text = "127.0.0.1"


$form1.Controls.Add($textBox1)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)

#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function


$global:connected=$false
#Call the Function
GenerateForm
