#$global:server = "http://localhost:8080/RaspiWeb/LedServlet"
$global:server = "http://service.joerg-tuttas.de:8081/Raspi/LedServlet"
#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 25.02.2015 13:10
# Generated By: Jörg
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$dimLable = New-Object System.Windows.Forms.Label
$checkBox1 = New-Object System.Windows.Forms.CheckBox
$trackBar1 = New-Object System.Windows.Forms.TrackBar
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$checkChanged= 
{
Write-Host $checkBox1
if($checkBox1.CheckState -eq 1) {
  $url = $global:server+"?out=plain&set=hight"
  Write-Host "Request $url";
  $result = Invoke-WebRequest $url
  $dimLable.Text=" LED $result %"
  $trackBar1.Value=100
}
else {
  $url = $global:server+"?out=plain&set=low"
  Write-Host "Request $url";
  $result = Invoke-WebRequest $url
  $dimLable.Text=" LED $result %"
  $trackBar1.Value=0
}


}

$valueChanged= 
{
  $url = $global:server+"?out=plain&dim="+$trackBar1.Value
  Write-Host "Request $url";
  $result = Invoke-WebRequest $url
  $dimLable.Text=" LED $result %"
  if ($trackBar1.Value -eq 0 ) {
    $checkBox1.Checked=$false
  }
  else {
    $checkBox1.Checked=$true
  }

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 261
$System_Drawing_Size.Width = 284
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "LED Control"

$dimLable.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 140
$System_Drawing_Point.Y = 12
$dimLable.Location = $System_Drawing_Point
$dimLable.Name = "dimLable"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$dimLable.Size = $System_Drawing_Size
$dimLable.TabIndex = 2
$dimLable.Text = "dim ?? %"

$form1.Controls.Add($dimLable)


$checkBox1.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 12
$checkBox1.Location = $System_Drawing_Point
$checkBox1.Name = "checkBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$checkBox1.Size = $System_Drawing_Size
$checkBox1.TabIndex = 1
$checkBox1.Text = "LED ON/OFF"
$checkBox1.UseVisualStyleBackColor = $True
$checkBox1.add_CheckedChanged($checkChanged)

$form1.Controls.Add($checkBox1)

$trackBar1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 71
$trackBar1.Location = $System_Drawing_Point
$trackBar1.Maximum = 100
$trackBar1.Name = "trackBar1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 45
$System_Drawing_Size.Width = 260
$trackBar1.Size = $System_Drawing_Size
$trackBar1.TabIndex = 0
$trackBar1.add_ValueChanged($valueChanged)

$form1.Controls.Add($trackBar1)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form

  $url = $global:server+"?out=xml"
  [xml]$result = Invoke-WebRequest $url
  $val=$result.led.dim
  $dimLable.Text=" LED $val %"
  if ($val -ne 0) {
    $checkBox1.Checked=$true
  }
  $trackBar1.Value=$val


$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
